### ISSUE TITLE
新数据库连接下的代码生成bug

### ISSUE THREAD

**Issue by kiba518** [Coldairarrow/Colder.Fx.Net.AdminLTE#2]
【代码生成】里，选择【数据库连接管理】里新添加的连接。
然后选择，新数据库里的表，生成代码后。
重启项目，点击刚配置好的menu，是不好使的。会查询数据库失败，因为连接字符串还是之前的，指向的数据库还是Colder.Fx.Net.AdminLTE。
需要在controller里修改代码创建Business的实体。
Kiba_UserBusiness _kiba_UserBusiness = new Kiba_UserBusiness(@"Data Source=.;Initial Catalog=Kiba;Integrated Security=True");
然后再在对应的Business类中增加构造函数才能好使。
public Kiba_UserBusiness(string connstr):base(connstr)
{ }
希望能优化这个问题，让代码生成更好使。

**Comment by Coldairarrow** [comment]
这个影响不大，多数据库只需要修改构造函数就可以了，工作量很低
框架的目的是尽量减少重复劳动力，并且是一个适当的度
